[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pytest-snob"
version = "0.1.0"
classifiers = [
    "Framework :: Pytest",
]

[project.entry-points.pytest11]
pytest-snob = "pytest_snob.plugin"
