name: ci-pytest-snob

on:
  push:
    branches:
      - main
    tags:
      - 'plugin@v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bump_package_version:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/plugin@v') }}
    steps:
      - name: extract version from tag
        # the # operator removes the "refs/tags/lib@v" part from the GITHUB_REF
        # in the end we're left with the version number, which we store in a GITHUB
        # environment variable
        run: echo "PYTEST_PLUGIN_PACKAGE_VERSION=${GITHUB_REF#refs/tags/plugin@v}" >> $GITHUB_ENV
      - name: replace version number in pyproject
        # using the environment variable we set up earlier to replace the version number in the pyproject.toml of the
        # pytest plugin
        run: sed -i "s/^version = .*$/version = \"{{ env.PYTEST_PLUGIN_PACKAGE_VERSION}}\"/" pytest-snob/pyproject.toml
        shell: bash
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build release distributions
        run: |
          cd pytest-snob
          # NOTE: put your own distribution build steps here.
          python -m pip install build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: pytest-snob-release-dists
          path: pytest-snob/dist/

  pypi-publish:
    if: ${{ startsWith(github.ref, 'refs/tags/plugin@v') }}
    runs-on: ubuntu-latest

    needs:
      - release-build

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    # Dedicated environments with protections for publishing are strongly recommended.
    environment:
      name: pypi
      # OPTIONAL: uncomment and update to include your PyPI project URL in the deployment status:
      url: https://pypi.org/p/pytest-snob

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: pytest-snob-release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://upload.pypi.org/legacy/
